mod 'puppet-nginx', '1.0.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs-translate'
mod 'samuelson-dockeragent', '1.0.0'
mod 'pltraining-dockeragent'
mod 'stahnma/epel'
mod 'garethr/docker'
